//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.27 at 05:44:00 PM COT 
//


package co.com.tucompra.validacionrest.dto;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for cuentaAhorroType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="cuentaAhorroType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="reclamo" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="llave" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="tipoLeyenda" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                 &lt;attribute name="fecha" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                 &lt;attribute name="estado" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                 &lt;attribute name="tipo" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                 &lt;attribute name="ratificado" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                 &lt;attribute name="fechaCierre" type="{http://www.w3.org/2001/XMLSchema}long" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="adjetivo" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="llave" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="codigo" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                 &lt;attribute name="fecha" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="llave" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="estado" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="entidad" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ultimaActualizacion" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="numeroCuenta" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="fechaApertura" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="oficina" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ciudad" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="bloqueada" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="codSuscriptor" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="situacionTitular" type="{http://www.w3.org/2001/XMLSchema}short" />
 *       &lt;attribute name="independiente">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "cuentaAhorroType", propOrder = {
    "reclamo",
    "adjetivo",
    "llave"
})
@XmlSeeAlso({
	co.com.tucompra.validacionrest.dto.Informe.CuentaAhorro.class
})
public class CuentaAhorroType {

    protected CuentaAhorroType.Reclamo reclamo;
    protected List<CuentaAhorroType.Adjetivo> adjetivo;
    protected Object llave;
    @XmlAttribute(name = "estado", required = true)
    protected String estado;
    @XmlAttribute(name = "entidad", required = true)
    protected String entidad;
    @XmlAttribute(name = "ultimaActualizacion", required = true)
    protected long ultimaActualizacion;
    @XmlAttribute(name = "numeroCuenta", required = true)
    protected String numeroCuenta;
    @XmlAttribute(name = "fechaApertura", required = true)
    protected long fechaApertura;
    @XmlAttribute(name = "oficina", required = true)
    protected String oficina;
    @XmlAttribute(name = "ciudad")
    protected String ciudad;
    @XmlAttribute(name = "bloqueada", required = true)
    protected boolean bloqueada;
    @XmlAttribute(name = "codSuscriptor")
    protected String codSuscriptor;
    @XmlAttribute(name = "situacionTitular")
    protected Short situacionTitular;
    @XmlAttribute(name = "independiente")
    protected String independiente;

    /**
     * Gets the value of the reclamo property.
     * 
     * @return
     *     possible object is
     *     {@link CuentaAhorroType.Reclamo }
     *     
     */
    public CuentaAhorroType.Reclamo getReclamo() {
        return reclamo;
    }

    /**
     * Sets the value of the reclamo property.
     * 
     * @param value
     *     allowed object is
     *     {@link CuentaAhorroType.Reclamo }
     *     
     */
    public void setReclamo(CuentaAhorroType.Reclamo value) {
        this.reclamo = value;
    }

    /**
     * Gets the value of the adjetivo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the adjetivo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdjetivo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CuentaAhorroType.Adjetivo }
     * 
     * 
     */
    public List<CuentaAhorroType.Adjetivo> getAdjetivo() {
        if (adjetivo == null) {
            adjetivo = new ArrayList<CuentaAhorroType.Adjetivo>();
        }
        return this.adjetivo;
    }

    /**
     * Gets the value of the llave property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getLlave() {
        return llave;
    }

    /**
     * Sets the value of the llave property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setLlave(Object value) {
        this.llave = value;
    }

    /**
     * Gets the value of the estado property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEstado() {
        return estado;
    }

    /**
     * Sets the value of the estado property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEstado(String value) {
        this.estado = value;
    }

    /**
     * Gets the value of the entidad property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntidad() {
        return entidad;
    }

    /**
     * Sets the value of the entidad property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntidad(String value) {
        this.entidad = value;
    }

    /**
     * Gets the value of the ultimaActualizacion property.
     * 
     */
    public long getUltimaActualizacion() {
        return ultimaActualizacion;
    }

    /**
     * Sets the value of the ultimaActualizacion property.
     * 
     */
    public void setUltimaActualizacion(long value) {
        this.ultimaActualizacion = value;
    }

    /**
     * Gets the value of the numeroCuenta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroCuenta() {
        return numeroCuenta;
    }

    /**
     * Sets the value of the numeroCuenta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroCuenta(String value) {
        this.numeroCuenta = value;
    }

    /**
     * Gets the value of the fechaApertura property.
     * 
     */
    public long getFechaApertura() {
        return fechaApertura;
    }

    /**
     * Sets the value of the fechaApertura property.
     * 
     */
    public void setFechaApertura(long value) {
        this.fechaApertura = value;
    }

    /**
     * Gets the value of the oficina property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOficina() {
        return oficina;
    }

    /**
     * Sets the value of the oficina property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOficina(String value) {
        this.oficina = value;
    }

    /**
     * Gets the value of the ciudad property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCiudad() {
        return ciudad;
    }

    /**
     * Sets the value of the ciudad property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCiudad(String value) {
        this.ciudad = value;
    }

    /**
     * Gets the value of the bloqueada property.
     * 
     */
    public boolean isBloqueada() {
        return bloqueada;
    }

    /**
     * Sets the value of the bloqueada property.
     * 
     */
    public void setBloqueada(boolean value) {
        this.bloqueada = value;
    }

    /**
     * Gets the value of the codSuscriptor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodSuscriptor() {
        return codSuscriptor;
    }

    /**
     * Sets the value of the codSuscriptor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodSuscriptor(String value) {
        this.codSuscriptor = value;
    }

    /**
     * Gets the value of the situacionTitular property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getSituacionTitular() {
        return situacionTitular;
    }

    /**
     * Sets the value of the situacionTitular property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setSituacionTitular(Short value) {
        this.situacionTitular = value;
    }

    /**
     * Gets the value of the independiente property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndependiente() {
        return independiente;
    }

    /**
     * Sets the value of the independiente property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndependiente(String value) {
        this.independiente = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="llave" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="codigo" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *       &lt;attribute name="fecha" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "llave"
    })
    public static class Adjetivo {

        protected Object llave;
        @XmlAttribute(name = "codigo", required = true)
        @XmlSchemaType(name = "anySimpleType")
        protected String codigo;
        @XmlAttribute(name = "fecha", required = true)
        protected long fecha;

        /**
         * Gets the value of the llave property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getLlave() {
            return llave;
        }

        /**
         * Sets the value of the llave property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setLlave(Object value) {
            this.llave = value;
        }

        /**
         * Gets the value of the codigo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCodigo() {
            return codigo;
        }

        /**
         * Sets the value of the codigo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCodigo(String value) {
            this.codigo = value;
        }

        /**
         * Gets the value of the fecha property.
         * 
         */
        public long getFecha() {
            return fecha;
        }

        /**
         * Sets the value of the fecha property.
         * 
         */
        public void setFecha(long value) {
            this.fecha = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="llave" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="tipoLeyenda" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *       &lt;attribute name="fecha" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
     *       &lt;attribute name="estado" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *       &lt;attribute name="tipo" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *       &lt;attribute name="ratificado" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *       &lt;attribute name="fechaCierre" type="{http://www.w3.org/2001/XMLSchema}long" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "llave"
    })
    public static class Reclamo {

        protected Object llave;
        @XmlAttribute(name = "tipoLeyenda")
        @XmlSchemaType(name = "anySimpleType")
        protected String tipoLeyenda;
        @XmlAttribute(name = "fecha", required = true)
        protected long fecha;
        @XmlAttribute(name = "estado", required = true)
        @XmlSchemaType(name = "anySimpleType")
        protected String estado;
        @XmlAttribute(name = "tipo")
        @XmlSchemaType(name = "anySimpleType")
        protected String tipo;
        @XmlAttribute(name = "ratificado", required = true)
        protected boolean ratificado;
        @XmlAttribute(name = "fechaCierre")
        protected Long fechaCierre;

        /**
         * Gets the value of the llave property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getLlave() {
            return llave;
        }

        /**
         * Sets the value of the llave property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setLlave(Object value) {
            this.llave = value;
        }

        /**
         * Gets the value of the tipoLeyenda property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTipoLeyenda() {
            return tipoLeyenda;
        }

        /**
         * Sets the value of the tipoLeyenda property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTipoLeyenda(String value) {
            this.tipoLeyenda = value;
        }

        /**
         * Gets the value of the fecha property.
         * 
         */
        public long getFecha() {
            return fecha;
        }

        /**
         * Sets the value of the fecha property.
         * 
         */
        public void setFecha(long value) {
            this.fecha = value;
        }

        /**
         * Gets the value of the estado property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEstado() {
            return estado;
        }

        /**
         * Sets the value of the estado property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEstado(String value) {
            this.estado = value;
        }

        /**
         * Gets the value of the tipo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTipo() {
            return tipo;
        }

        /**
         * Sets the value of the tipo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTipo(String value) {
            this.tipo = value;
        }

        /**
         * Gets the value of the ratificado property.
         * 
         */
        public boolean isRatificado() {
            return ratificado;
        }

        /**
         * Sets the value of the ratificado property.
         * 
         */
        public void setRatificado(boolean value) {
            this.ratificado = value;
        }

        /**
         * Gets the value of the fechaCierre property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        public Long getFechaCierre() {
            return fechaCierre;
        }

        /**
         * Sets the value of the fechaCierre property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setFechaCierre(Long value) {
            this.fechaCierre = value;
        }

    }

}
