//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.27 at 05:44:00 PM COT 
//


package co.com.tucompra.validacionrest.dto;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tarjetaCreditoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tarjetaCreditoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="valores" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="cupo" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                 &lt;attribute name="saldoActual" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                 &lt;attribute name="saldoMora" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                 &lt;attribute name="cuota" type="{http://www.w3.org/2001/XMLSchema}double" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="reclamo" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="llave" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="tipoLeyenda" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                 &lt;attribute name="fechaCierre" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                 &lt;attribute name="estado" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                 &lt;attribute name="tipo" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                 &lt;attribute name="fecha" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                 &lt;attribute name="ratificado" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="adjetivo" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="llave" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="codigo" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                 &lt;attribute name="fecha" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="alivio" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="estado" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="mes" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="llave" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="estado" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="estado48" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="entidad" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ultimaActualizacion" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="numero" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="fechaApertura" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="fechaVencimiento" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="comportamiento" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="amparada" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="formaPago" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="bloqueada" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="codSuscriptor" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="positivoNegativo" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="oficina" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="situacionTitular" use="required" type="{http://www.w3.org/2001/XMLSchema}short" />
 *       &lt;attribute name="estadoOrigen" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="prescripcion" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="independiente">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="insoluta" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="estadoCuenta">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tarjetaCreditoType", propOrder = {
    "valores",
    "reclamo",
    "adjetivo",
    "alivio",
    "llave"
})
public class TarjetaCreditoType {

    protected TarjetaCreditoType.Valores valores;
    protected TarjetaCreditoType.Reclamo reclamo;
    protected List<TarjetaCreditoType.Adjetivo> adjetivo;
    protected TarjetaCreditoType.Alivio alivio;
    protected Object llave;
    @XmlAttribute(name = "estado", required = true)
    protected String estado;
    @XmlAttribute(name = "estado48")
    protected String estado48;
    @XmlAttribute(name = "entidad", required = true)
    protected String entidad;
    @XmlAttribute(name = "ultimaActualizacion", required = true)
    protected long ultimaActualizacion;
    @XmlAttribute(name = "numero", required = true)
    protected String numero;
    @XmlAttribute(name = "fechaApertura", required = true)
    protected long fechaApertura;
    @XmlAttribute(name = "fechaVencimiento", required = true)
    protected long fechaVencimiento;
    @XmlAttribute(name = "comportamiento")
    protected String comportamiento;
    @XmlAttribute(name = "amparada", required = true)
    protected boolean amparada;
    @XmlAttribute(name = "formaPago")
    protected String formaPago;
    @XmlAttribute(name = "bloqueada", required = true)
    protected boolean bloqueada;
    @XmlAttribute(name = "codSuscriptor")
    protected String codSuscriptor;
    @XmlAttribute(name = "positivoNegativo", required = true)
    protected String positivoNegativo;
    @XmlAttribute(name = "oficina", required = true)
    protected String oficina;
    @XmlAttribute(name = "situacionTitular", required = true)
    protected short situacionTitular;
    @XmlAttribute(name = "estadoOrigen", required = true)
    protected String estadoOrigen;
    @XmlAttribute(name = "prescripcion")
    protected String prescripcion;
    @XmlAttribute(name = "independiente")
    protected String independiente;
    @XmlAttribute(name = "insoluta")
    protected String insoluta;
    @XmlAttribute(name = "estadoCuenta")
    protected String estadoCuenta;

    /**
     * Gets the value of the valores property.
     * 
     * @return
     *     possible object is
     *     {@link TarjetaCreditoType.Valores }
     *     
     */
    public TarjetaCreditoType.Valores getValores() {
        return valores;
    }

    /**
     * Sets the value of the valores property.
     * 
     * @param value
     *     allowed object is
     *     {@link TarjetaCreditoType.Valores }
     *     
     */
    public void setValores(TarjetaCreditoType.Valores value) {
        this.valores = value;
    }

    /**
     * Gets the value of the reclamo property.
     * 
     * @return
     *     possible object is
     *     {@link TarjetaCreditoType.Reclamo }
     *     
     */
    public TarjetaCreditoType.Reclamo getReclamo() {
        return reclamo;
    }

    /**
     * Sets the value of the reclamo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TarjetaCreditoType.Reclamo }
     *     
     */
    public void setReclamo(TarjetaCreditoType.Reclamo value) {
        this.reclamo = value;
    }

    /**
     * Gets the value of the adjetivo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the adjetivo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdjetivo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TarjetaCreditoType.Adjetivo }
     * 
     * 
     */
    public List<TarjetaCreditoType.Adjetivo> getAdjetivo() {
        if (adjetivo == null) {
            adjetivo = new ArrayList<TarjetaCreditoType.Adjetivo>();
        }
        return this.adjetivo;
    }

    /**
     * Gets the value of the alivio property.
     * 
     * @return
     *     possible object is
     *     {@link TarjetaCreditoType.Alivio }
     *     
     */
    public TarjetaCreditoType.Alivio getAlivio() {
        return alivio;
    }

    /**
     * Sets the value of the alivio property.
     * 
     * @param value
     *     allowed object is
     *     {@link TarjetaCreditoType.Alivio }
     *     
     */
    public void setAlivio(TarjetaCreditoType.Alivio value) {
        this.alivio = value;
    }

    /**
     * Gets the value of the llave property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getLlave() {
        return llave;
    }

    /**
     * Sets the value of the llave property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setLlave(Object value) {
        this.llave = value;
    }

    /**
     * Gets the value of the estado property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEstado() {
        return estado;
    }

    /**
     * Sets the value of the estado property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEstado(String value) {
        this.estado = value;
    }

    /**
     * Gets the value of the estado48 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEstado48() {
        return estado48;
    }

    /**
     * Sets the value of the estado48 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEstado48(String value) {
        this.estado48 = value;
    }

    /**
     * Gets the value of the entidad property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntidad() {
        return entidad;
    }

    /**
     * Sets the value of the entidad property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntidad(String value) {
        this.entidad = value;
    }

    /**
     * Gets the value of the ultimaActualizacion property.
     * 
     */
    public long getUltimaActualizacion() {
        return ultimaActualizacion;
    }

    /**
     * Sets the value of the ultimaActualizacion property.
     * 
     */
    public void setUltimaActualizacion(long value) {
        this.ultimaActualizacion = value;
    }

    /**
     * Gets the value of the numero property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumero() {
        return numero;
    }

    /**
     * Sets the value of the numero property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumero(String value) {
        this.numero = value;
    }

    /**
     * Gets the value of the fechaApertura property.
     * 
     */
    public long getFechaApertura() {
        return fechaApertura;
    }

    /**
     * Sets the value of the fechaApertura property.
     * 
     */
    public void setFechaApertura(long value) {
        this.fechaApertura = value;
    }

    /**
     * Gets the value of the fechaVencimiento property.
     * 
     */
    public long getFechaVencimiento() {
        return fechaVencimiento;
    }

    /**
     * Sets the value of the fechaVencimiento property.
     * 
     */
    public void setFechaVencimiento(long value) {
        this.fechaVencimiento = value;
    }

    /**
     * Gets the value of the comportamiento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComportamiento() {
        return comportamiento;
    }

    /**
     * Sets the value of the comportamiento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComportamiento(String value) {
        this.comportamiento = value;
    }

    /**
     * Gets the value of the amparada property.
     * 
     */
    public boolean isAmparada() {
        return amparada;
    }

    /**
     * Sets the value of the amparada property.
     * 
     */
    public void setAmparada(boolean value) {
        this.amparada = value;
    }

    /**
     * Gets the value of the formaPago property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormaPago() {
        return formaPago;
    }

    /**
     * Sets the value of the formaPago property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormaPago(String value) {
        this.formaPago = value;
    }

    /**
     * Gets the value of the bloqueada property.
     * 
     */
    public boolean isBloqueada() {
        return bloqueada;
    }

    /**
     * Sets the value of the bloqueada property.
     * 
     */
    public void setBloqueada(boolean value) {
        this.bloqueada = value;
    }

    /**
     * Gets the value of the codSuscriptor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodSuscriptor() {
        return codSuscriptor;
    }

    /**
     * Sets the value of the codSuscriptor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodSuscriptor(String value) {
        this.codSuscriptor = value;
    }

    /**
     * Gets the value of the positivoNegativo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPositivoNegativo() {
        return positivoNegativo;
    }

    /**
     * Sets the value of the positivoNegativo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPositivoNegativo(String value) {
        this.positivoNegativo = value;
    }

    /**
     * Gets the value of the oficina property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOficina() {
        return oficina;
    }

    /**
     * Sets the value of the oficina property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOficina(String value) {
        this.oficina = value;
    }

    /**
     * Gets the value of the situacionTitular property.
     * 
     */
    public short getSituacionTitular() {
        return situacionTitular;
    }

    /**
     * Sets the value of the situacionTitular property.
     * 
     */
    public void setSituacionTitular(short value) {
        this.situacionTitular = value;
    }

    /**
     * Gets the value of the estadoOrigen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEstadoOrigen() {
        return estadoOrigen;
    }

    /**
     * Sets the value of the estadoOrigen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEstadoOrigen(String value) {
        this.estadoOrigen = value;
    }

    /**
     * Gets the value of the prescripcion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrescripcion() {
        return prescripcion;
    }

    /**
     * Sets the value of the prescripcion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrescripcion(String value) {
        this.prescripcion = value;
    }

    /**
     * Gets the value of the independiente property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndependiente() {
        return independiente;
    }

    /**
     * Sets the value of the independiente property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndependiente(String value) {
        this.independiente = value;
    }

    /**
     * Gets the value of the insoluta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInsoluta() {
        return insoluta;
    }

    /**
     * Sets the value of the insoluta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInsoluta(String value) {
        this.insoluta = value;
    }

    /**
     * Gets the value of the estadoCuenta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEstadoCuenta() {
        return estadoCuenta;
    }

    /**
     * Sets the value of the estadoCuenta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEstadoCuenta(String value) {
        this.estadoCuenta = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="llave" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="codigo" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *       &lt;attribute name="fecha" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "llave"
    })
    public static class Adjetivo {

        protected Object llave;
        @XmlAttribute(name = "codigo", required = true)
        @XmlSchemaType(name = "anySimpleType")
        protected String codigo;
        @XmlAttribute(name = "fecha", required = true)
        protected long fecha;

        /**
         * Gets the value of the llave property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getLlave() {
            return llave;
        }

        /**
         * Sets the value of the llave property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setLlave(Object value) {
            this.llave = value;
        }

        /**
         * Gets the value of the codigo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCodigo() {
            return codigo;
        }

        /**
         * Sets the value of the codigo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCodigo(String value) {
            this.codigo = value;
        }

        /**
         * Gets the value of the fecha property.
         * 
         */
        public long getFecha() {
            return fecha;
        }

        /**
         * Sets the value of the fecha property.
         * 
         */
        public void setFecha(long value) {
            this.fecha = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="estado" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="mes" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Alivio {

        @XmlAttribute(name = "estado", required = true)
        protected String estado;
        @XmlAttribute(name = "mes", required = true)
        protected String mes;

        /**
         * Gets the value of the estado property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEstado() {
            return estado;
        }

        /**
         * Sets the value of the estado property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEstado(String value) {
            this.estado = value;
        }

        /**
         * Gets the value of the mes property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMes() {
            return mes;
        }

        /**
         * Sets the value of the mes property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMes(String value) {
            this.mes = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="llave" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="tipoLeyenda" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *       &lt;attribute name="fechaCierre" type="{http://www.w3.org/2001/XMLSchema}long" />
     *       &lt;attribute name="estado" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *       &lt;attribute name="tipo" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *       &lt;attribute name="fecha" type="{http://www.w3.org/2001/XMLSchema}long" />
     *       &lt;attribute name="ratificado" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "llave"
    })
    public static class Reclamo {

        protected Object llave;
        @XmlAttribute(name = "tipoLeyenda")
        @XmlSchemaType(name = "anySimpleType")
        protected String tipoLeyenda;
        @XmlAttribute(name = "fechaCierre")
        protected Long fechaCierre;
        @XmlAttribute(name = "estado", required = true)
        @XmlSchemaType(name = "anySimpleType")
        protected String estado;
        @XmlAttribute(name = "tipo", required = true)
        @XmlSchemaType(name = "anySimpleType")
        protected String tipo;
        @XmlAttribute(name = "fecha")
        protected Long fecha;
        @XmlAttribute(name = "ratificado", required = true)
        protected boolean ratificado;

        /**
         * Gets the value of the llave property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getLlave() {
            return llave;
        }

        /**
         * Sets the value of the llave property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setLlave(Object value) {
            this.llave = value;
        }

        /**
         * Gets the value of the tipoLeyenda property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTipoLeyenda() {
            return tipoLeyenda;
        }

        /**
         * Sets the value of the tipoLeyenda property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTipoLeyenda(String value) {
            this.tipoLeyenda = value;
        }

        /**
         * Gets the value of the fechaCierre property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        public Long getFechaCierre() {
            return fechaCierre;
        }

        /**
         * Sets the value of the fechaCierre property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setFechaCierre(Long value) {
            this.fechaCierre = value;
        }

        /**
         * Gets the value of the estado property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEstado() {
            return estado;
        }

        /**
         * Sets the value of the estado property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEstado(String value) {
            this.estado = value;
        }

        /**
         * Gets the value of the tipo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTipo() {
            return tipo;
        }

        /**
         * Sets the value of the tipo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTipo(String value) {
            this.tipo = value;
        }

        /**
         * Gets the value of the fecha property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        public Long getFecha() {
            return fecha;
        }

        /**
         * Sets the value of the fecha property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setFecha(Long value) {
            this.fecha = value;
        }

        /**
         * Gets the value of the ratificado property.
         * 
         */
        public boolean isRatificado() {
            return ratificado;
        }

        /**
         * Sets the value of the ratificado property.
         * 
         */
        public void setRatificado(boolean value) {
            this.ratificado = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="cupo" type="{http://www.w3.org/2001/XMLSchema}double" />
     *       &lt;attribute name="saldoActual" type="{http://www.w3.org/2001/XMLSchema}double" />
     *       &lt;attribute name="saldoMora" type="{http://www.w3.org/2001/XMLSchema}double" />
     *       &lt;attribute name="cuota" type="{http://www.w3.org/2001/XMLSchema}double" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Valores {

        @XmlAttribute(name = "cupo")
        protected Double cupo;
        @XmlAttribute(name = "saldoActual")
        protected Double saldoActual;
        @XmlAttribute(name = "saldoMora")
        protected Double saldoMora;
        @XmlAttribute(name = "cuota")
        protected Double cuota;

        /**
         * Gets the value of the cupo property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getCupo() {
            return cupo;
        }

        /**
         * Sets the value of the cupo property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setCupo(Double value) {
            this.cupo = value;
        }

        /**
         * Gets the value of the saldoActual property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getSaldoActual() {
            return saldoActual;
        }

        /**
         * Sets the value of the saldoActual property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setSaldoActual(Double value) {
            this.saldoActual = value;
        }

        /**
         * Gets the value of the saldoMora property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getSaldoMora() {
            return saldoMora;
        }

        /**
         * Sets the value of the saldoMora property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setSaldoMora(Double value) {
            this.saldoMora = value;
        }

        /**
         * Gets the value of the cuota property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getCuota() {
            return cuota;
        }

        /**
         * Sets the value of the cuota property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setCuota(Double value) {
            this.cuota = value;
        }

    }

}
